name: "Gazetta Studio"
targets:
  production:
    storage:
      type: r2
      accountId: "30ec7440a8cdafa137c993cd4a0f4c67"
      bucket: "gazetta-studio-site"
      accessKeyId: "${R2_ACCESS_KEY_ID}"
      secretAccessKey: "${R2_SECRET_ACCESS_KEY}"
    worker:
      type: cloudflare
      name: gazetta-studio
    siteUrl: "https://gazetta.studio"
    cache:
      browser: 0
      edge: 86400
      purge:
        type: cloudflare
        apiToken: "${CLOUDFLARE_API_TOKEN}"
