name: "Gazetta Starter"
version: "1.0.0"
systemPages:
  - "404"
targets:
  staging:
    storage:
      type: filesystem
      path: ./dist/staging
  production:
    storage:
      type: azure-blob
      connectionString: "UseDevelopmentStorage=true"
      container: "gazetta-production"
